### ISSUE TITLE
YouTube Android Player API INTERNAL_ERROR for multiple videos

### ISSUE THREAD

**Issue by deepakswami7** [youtube/yt-android-player#11]
**Name of API affected: YouTube Android Player API**

**Issue summary:**
Using the YouTube Android Player API sample code (version 1.2.2), if I change any of the video IDs over to one I have uploaded (e.g. "QVikru_w2hQ" or "u1n6E81rm80"), the thumbnail loads in the player, but on clicking play, the player goes to the onError function with YouTubePlayer.ErrorReason.INTERNAL_ERROR. Playing these videos on the YouTube website or our iOS app does not have a problem.

**Steps to reproduce issue:**
1. Download YouTube Android Player API sample code (version 1.2.2).
2. Download YouTube Android app version 11.13.56.
3. Input developer key into player code.
4. Change any sample class YouTube video ID to "QVikru_w2hQ".
5. Run app and try to play video.

**Expected output:**
Video should play.

**Actual results:**
onError function called with YouTubePlayer.ErrorReason.INTERNAL_ERROR and message "There was a problem while playing. Tap to retry".

**Notes:**
I am experiencing this issue on multiple devices, including my Nexus 5X (android 6.0.1) with YouTube app version currently at 11.13.56.

*_Logcat: *_

05-08 11:25:22.145 20521-20521/? E/YouTubeAndroidPlayerAPI: fmt.noneavailable
oae: Video not supported/available
at oab.a(SourceFile:212)
at nvl.a(SourceFile:383)
at nvl.a(SourceFile:706)
at nvr.a(SourceFile:1144
at nsn.onPostExecute(SourceFile:2102)
at android.os.AsyncTask.finish(AsyncTask.java:651)
at android.os.AsyncTask.-wrap1(AsyncTask.java)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5443)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**The problem seems related to the date of publication of the video... In the last week of April I posted many videos on YouTube, those published up to 19:00 of April 27 work properly, while those charged by 21:15 on the same day have the issue discussed, as if between 19 and 21 of April 27 had been introduced a few updates or changes to the videos by YouTube. I tried to load a new video just now and this also has the same problem.**

**Comment by Laeyoung** [comment]
I've got the same issue
