### ISSUE TITLE
NullPointerException at onFilterTouchEventForSecurity

### ISSUE THREAD

**Issue by anonym24** [youtube/yt-android-player#22]
This error is quite popular now:

https://stackoverflow.com/questions/45172972/getting-nullpointerexception-at-onfiltertoucheventforsecurity

https://stackoverflow.com/questions/45857554/getting-lot-of-crashes-in-youtube-player-api

https://stackoverflow.com/questions/51654151/nullpointerexception-in-onfiltertoucheventforsecurity-with-youtubebaseactivity

and I guess this one too https://stackoverflow.com/questions/45003133/nullpointerexception-at-onfiltertoucheventforsecurity

(all users from StackOverflow use YouTube Android Player API)

Reports from Google Console

![image](https://user-images.githubusercontent.com/8851301/50729722-5ea91400-1147-11e9-8329-073968bae95b.png)

![image](https://user-images.githubusercontent.com/8851301/50729724-6668b880-1147-11e9-851c-5d1163d6b03e.png)

![image](https://user-images.githubusercontent.com/8851301/50729728-6f598a00-1147-11e9-95ed-17135c08bcbe.png)

```
java.lang.NullPointerException: 
  at ipf.onFilterTouchEventForSecurity(ipf.java:115)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2351)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2461)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2461)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2461)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2876)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2461)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
  at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2840)
  at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1853)
  at android.app.Activity.dispatchTouchEvent(Activity.java:3061)
  at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2801)
  at android.view.View.dispatchPointerEvent(View.java:10246)
  at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5447)
  at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5283)
  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4721)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4774)
  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4740)
  at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4882)
  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4748)
  at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4939)
  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4721)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4774)
  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4740)
  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4748)
  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4721)
  at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7429)
  at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7298)
  at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7259)
  at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7539)
  at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
  at android.os.MessageQueue.nativePollOnce(MessageQueue.java:0)
  at android.os.MessageQueue.next(MessageQueue.java:323)
  at android.os.Looper.loop(Looper.java:135)
  at android.app.ActivityThread.main(ActivityThread.java:7325)
  at java.lang.reflect.Method.invoke(Method.java:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by AbcEupho** [comment]
did anyone get solution to this issue?

**Comment by anonym24** [comment]
@AbcEupho I don't think so. And the library isn't open-sourced. So only Google Developers can fix it @ulukaya

**Comment by AbcEupho** [comment]
Then how to know the fix.. And how to contact google developers

**Comment by anonym24** [comment]
@AbcEupho seems this project was created by @ulukaya
And it seems he doesn't support it that hard. Mb he has other big projects.
But I hope that he didn't drop this one

**Comment by KaushikNisha26** [comment]
Any updates regarding this issue?

**Comment by anonym24** [comment]
@KaushikNisha26 why would ask this? Just read all comments above and answer on your question yourself. Such a weird question..

**Comment by edcastrohit** [comment]
i am also facing this issue, is any way to handle this crash.

**Comment by ThirupathiMukkera** [comment]
recently I got this crash, How to handle it

**Comment by bhaveshjabuvani88** [comment]
I got Same issue 
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void mpu.a(boolean)' on a null object reference

Anyone has found any solution?
